# Fleet Management Platform — Production Docker Compose
# Usage: docker compose -f compose.prod.yml up -d

services:
  # ─── Reverse Proxy (SSL) ────────────────────────
  caddy:
    image: caddy:2-alpine
    container_name: fleet-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443" # Disabled while using IP address to prevent SSL errors
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL_FOR_SSL: ${EMAIL_FOR_SSL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 256M

  # ─── PostgreSQL Database ────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: fleet-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      retries: 5
    networks:
      - db-net
    deploy:
      resources:
        limits:
          memory: 512M

  # ─── Backend API ────────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fleet-backend-prod
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/v1/health" ]
      interval: 10s
      timeout: 5s
      retries: 3
    environment:
      # These are now loaded from AWS Secrets Manager & SSM Parameter Store
      PORT: 3000
      NODE_ENV: production
      CORS_ORIGIN: http://${DOMAIN_NAME}
      FRONTEND_URL: ${FRONTEND_URL}
    networks:
      - db-net
      - app-net
    deploy:
      resources:
        limits:
          memory: 512M

  # ─── Frontend ───────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fleet-frontend-prod
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  db-net:
    internal: true # No internet access for the database
  app-net:
    # Default bridge network with internet access for backend/frontend

volumes:
  pgdata_prod:
  caddy_data:
  caddy_config:
