# Fleet Management Platform — Production Docker Compose
# Usage: docker compose -f compose.prod.yml up -d

services:
  # ─── Reverse Proxy (SSL) ────────────────────────
  caddy:
    image: caddy:2-alpine
    container_name: fleet-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      # - "443:443" # Disabled while using IP address to prevent SSL errors
    environment:
      DOMAIN_NAME: ${DOMAIN_NAME}
      EMAIL_FOR_SSL: ${EMAIL_FOR_SSL}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - frontend
      - backend

  # ─── PostgreSQL Database ────────────────────────
  postgres:
    image: postgres:16-alpine
    container_name: fleet-postgres-prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5

  # ─── Backend API ────────────────────────────────
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fleet-backend-prod
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      PORT: 3000
      NODE_ENV: production
      CORS_ORIGIN: http://${DOMAIN_NAME}
      S3_BUCKET: ${S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}

  # ─── Frontend ───────────────────────────────────
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fleet-frontend-prod
    restart: unless-stopped
    depends_on:
      - backend

volumes:
  pgdata_prod:
  caddy_data:
  caddy_config:
